### ISSUE TITLE
Extra octothorpe/pound/hash in background-color rule

### ISSUE THREAD

**Issue by miketaylr** [kremalicious/kbdfun#1]
See https://github.com/kremalicious/kbdfun/blob/master/assets/css/kbdfun.css#L59

``` css
kbd.ios {
...
background-color: ##b7b7bc;
...
}
```

It's also in the site.css as well. Leftovers from debugging?
